name: Executar STR2.py

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Executar script STR2.py
      run: python STR2.py


         
         
      
    - name: Add Changes to Git
      run: |
          git add -A
          ls -la 
          
      # Commit and Push changes
    - name: Commit & Push
      run: |
          git commit -m "links atualizados"
          git push
