name: Executar STR2.py

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: config
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        
        # Installing streamlink
    - name: Atualizar branch local com as alterações remotas
      run: git pull origin main
      
    - name: Install streamlink
      run: |
          pip install --user --upgrade streamlink   
          
      # Installing dependencies
    - name: Install dependencies
      run: |
          pip install youtube-dl 
          pip install requests 
          pip install beautifulsoup4 
          pip install fastapi 
          pip install uvicorn 
          pip install schedule
          pip install selenium
          pip install datetime
          pip install pytz
          pip install google-api-python-client
          
    - name: Executar script STR2.py
      run: python STR2.py
    - name: Fazer push das alterações para o Github
      run: |
        git add .
        git commit -m "Adiciona arquivo STR2.py"
        git push origin main
